# This is a basic workflow that is manually triggered
name: PyInstaller Manual Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: "Release Name"
        required: true
        default: "YouTube_Downloader"
      tag_name:
        description: "Tag Name"
        required: true
        default: "v0.2.2"
      release_body:
        description: "Release Body"
        required: false

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Create Windows Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.12"
          spec: "ytDL.py"
          requirements: "requirements.txt"
          upload_exe_with_name: "YouTube_Downloader-Windows"
          options: '--onefile --add-data "img:img" --noconsole --name "YouTube_Downloader"'

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Linux Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.12"
          spec: "ytDL.py"
          requirements: "requirements.txt"
          upload_exe_with_name: "YouTube_Downloader-Linux"
          options: '--onefile --add-data "img:img" --noconsole --name "YouTube_Downloader"'

  build_macos:
    runs-on: macos-latest
    steps:
      - name: Create MacOS Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.12"
          spec: "ytDL.py"
          requirements: "requirements.txt"
          upload_exe_with_name: "YouTube_Downloader-MacOS"
          options: '--onefile --add-data "img:img" --noconsole --name "YouTube_Downloader"'
