# This is a basic workflow that is manually triggered
name: PyInstaller Manual Build 

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release Name'
        required: true
        default: 'YouTube_Downloader'
      tag_name:
        description: 'Tag Name'
        required: true
        default: 'v0.2.2'

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Create Windows Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'ytDL.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'YouTube_Downloader-Windows'
          options: '--onefile --noconsole --name "YouTube_Downloader" --windowed'

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Linux Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'ytDL.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'YouTube_Downloader-Linux'
          options: '--onefile --noconsole --name "YouTube_Downloader"'

  build_macos:
    runs-on: macos-latest
    steps:
      - name: Create MacOS Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'ytDL.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'YouTube_Downloader-MacOS'
          options: '--onefile --noconsole --name "YouTube_Downloader"'

  release_upload:
    runs-on: ubuntu-latest
    needs: [build_windows, build_linux, build_macos]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prompt for Input
        run: |
          echo "Enter Release Name (press Enter to use default: 'YouTube_Downloader')"
          read RELEASE_NAME
          echo "Enter Tag Name (press Enter to use default: 'v0.2.2')"
          read TAG_NAME
        env:
          RELEASE_NAME: ${{ RELEASE_NAME }}
          TAG_NAME: ${{ TAG_NAME }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: true
          prerelease: false

      - name: Upload Release Assets
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            ./dist/YouTube_Downloader-Windows.exe
            ./dist/YouTube_Downloader-Linux
            ./dist/YouTube_Downloader-MacOS
          asset_name: YouTube_Downloader
          asset_content_type: application/octet-stream
